/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_epc_vsp_vsprepository_jni_FbxParse */

#ifndef _Included_com_epc_vsp_vsprepository_jni_FbxParse
#define _Included_com_epc_vsp_vsprepository_jni_FbxParse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_epc_vsp_vsprepository_jni_FbxParse
 * Method:    initFbxManager
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_epc_vsp_vsprepository_jni_FbxParse_initFbxManager
  (JNIEnv *, jobject);

/*
 * Class:     com_epc_vsp_vsprepository_jni_FbxParse
 * Method:    loadFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_epc_vsp_vsprepository_jni_FbxParse_loadFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_epc_vsp_vsprepository_jni_FbxParse
 * Method:    converTriangulate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_epc_vsp_vsprepository_jni_FbxParse_converTriangulate
  (JNIEnv *, jobject);

/*
 * Class:     com_epc_vsp_vsprepository_jni_FbxParse
 * Method:    getCenterPoint
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_epc_vsp_vsprepository_jni_FbxParse_getCenterPoint
  (JNIEnv *, jobject);

/*
 * Class:     com_epc_vsp_vsprepository_jni_FbxParse
 * Method:    getMaterials
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_epc_vsp_vsprepository_jni_FbxParse_getMaterials
  (JNIEnv *, jobject);

/*
 * Class:     com_epc_vsp_vsprepository_jni_FbxParse
 * Method:    getCoordinates
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_epc_vsp_vsprepository_jni_FbxParse_getCoordinates
  (JNIEnv *, jobject);

/*
 * Class:     com_epc_vsp_vsprepository_jni_FbxParse
 * Method:    destory
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_epc_vsp_vsprepository_jni_FbxParse_destory
  (JNIEnv *, jobject);

/*
 * Class:     com_epc_vsp_vsprepository_jni_FbxParse
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_epc_vsp_vsprepository_jni_FbxParse_sayHello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
